-module(kvs).

-export([filter/2,
         find/2,
         fold/3,
         from_proplist/1,
         get/2, get/3,
         is_key/2,
         iterator/1,
         keys/1,
         map/2,
         merge/2,
         new/0,
         next/1,
         put/3,
         remove/2,
         size/1,
         take/2,
         to_list/1,
         update/3,
         update_with/3, update_with/4,
         values/1,
         with/2,
         without/2]).
